const {app,BrowserWindow,ipcMain,desktopCapturer,session,Tray,Menu,nativeImage}=require('electron');const path=require('path');const {spawn}=require('child_process');let engine,aura,screenSourceId=null,mainWindow,tray,isQuitting=false,razerGuard;
function suppressRazerLighting(){for(const name of ['RazerAppEngine.exe','RzChromaConnectManager.exe','RzChromaConnectServer.exe'])spawn('taskkill',['/F','/IM',name],{windowsHide:true,stdio:'ignore'}).on('error',()=>{})}
function trayIcon(){return nativeImage.createFromPath(path.join(__dirname,'assets','icon.png')).resize({width:24,height:24})}
function create(){mainWindow=new BrowserWindow({width:1180,height:760,minWidth:980,minHeight:650,frame:false,transparent:true,backgroundColor:'#00000000',webPreferences:{preload:path.join(__dirname,'preload.js')}});mainWindow.loadFile('ui/index.html');mainWindow.on('close',e=>{if(!isQuitting){e.preventDefault();mainWindow.hide()}});tray=new Tray(trayIcon());tray.setToolTip('Chroma Sync Studio');tray.setContextMenu(Menu.buildFromTemplate([{label:'Open Chroma Sync Studio',click:()=>{mainWindow.show();mainWindow.focus()}},{type:'separator'},{label:'Exit',click:()=>{isQuitting=true;app.quit()}}]));tray.on('double-click',()=>{mainWindow.show();mainWindow.focus()})}
let booted=false;
function boot(){if(booted)return;booted=true;app.whenReady().then(()=>{suppressRazerLighting();razerGuard=setInterval(suppressRazerLighting,2500);session.defaultSession.setDisplayMediaRequestHandler(async(_,callback)=>{const list=await desktopCapturer.getSources({types:['screen','window']});callback({video:list.find(s=>s.id===screenSourceId)||list[0],audio:'loopback'})});engine=spawn('python',[path.join(__dirname,'engine.py')],{stdio:['pipe','pipe','pipe'],windowsHide:true});engine.stderr.on('data',d=>console.error(String(d)));aura=spawn(path.join(__dirname,'AuraReceiver.exe'),[],{stdio:['pipe','pipe','pipe'],windowsHide:true});aura.stderr.on('data',d=>console.error(String(d)));create()})}
app.on('second-instance',()=>{isQuitting=true;app.quit()});
if(app.requestSingleInstanceLock({replace:true}))boot();else{const takeover=setInterval(()=>{if(app.requestSingleInstanceLock({replace:true})){clearInterval(takeover);boot()}},100)}
ipcMain.handle('status',()=>({soyo:!!engine&&!engine.killed,razer:!!engine&&!engine.killed,ares:!!aura&&!aura.killed&&aura.exitCode===null}));
ipcMain.handle('set-frame',(_,x)=>{if(engine&&!engine.killed)engine.stdin.write(JSON.stringify(x)+'\n');if(x.useAres&&aura&&!aura.killed&&aura.exitCode===null)aura.stdin.write(`${x.red} ${x.green} ${x.blue}\n`);return true});
async function sources(size={width:320,height:180}){return desktopCapturer.getSources({types:['screen','window'],thumbnailSize:size,fetchWindowIcons:false})}
ipcMain.handle('screen-sources',async()=>{const list=await sources();if(!screenSourceId&&list[0])screenSourceId=list[0].id;return list.map(s=>({id:s.id,name:s.name,preview:s.thumbnail.isEmpty()?'':s.thumbnail.toDataURL(),selected:s.id===screenSourceId}))});
ipcMain.handle('select-screen-source',(_,id)=>{screenSourceId=id;return true});
ipcMain.handle('screen-color',async()=>{const list=await sources({width:160,height:90});const src=list.find(s=>s.id===screenSourceId)||list[0];if(!src||src.thumbnail.isEmpty())return{ok:false,color:[80,80,80],preview:''};screenSourceId=src.id;const b=src.thumbnail.toBitmap();let r=0,g=0,bl=0,w=0;for(let i=0;i<b.length;i+=4){const B=b[i],G=b[i+1],R=b[i+2],mx=Math.max(R,G,B),mn=Math.min(R,G,B);if(mx<25)continue;const q=12+mx-mn;r+=R*q;g+=G*q;bl+=B*q;w+=q}return{ok:true,color:w?[Math.round(r/w),Math.round(g/w),Math.round(bl/w)]:[0,0,0],preview:src.thumbnail.toDataURL(),name:src.name}});
ipcMain.on('window-minimize',e=>BrowserWindow.fromWebContents(e.sender).minimize());ipcMain.on('window-close',e=>BrowserWindow.fromWebContents(e.sender).close());
app.on('before-quit',()=>{isQuitting=true;if(razerGuard)clearInterval(razerGuard);if(engine)engine.kill();if(aura)aura.kill()});app.on('window-all-closed',()=>{});
