let effect='music',running=true,t=0,busy=false;
const $=s=>document.querySelector(s),toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)};
function hexrgb(h){return[h.slice(1,3),h.slice(3,5),h.slice(5,7)].map(x=>parseInt(x,16))}function hsv(h,s,v){let f=(n,k=(n+h/60)%6)=>v-v*s*Math.max(0,Math.min(k,4-k,1));return[f(5),f(3),f(1)].map(x=>Math.round(x*255))}
let captureStream=null,lastColor=[80,80,80],audioCtx=null,analyser=null,audioData=null,peak=0;
async function startCapture(){if(captureStream)captureStream.getTracks().forEach(x=>x.stop());try{captureStream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:60,max:60},width:{ideal:640},height:{ideal:360}},audio:true});const v=$('#capture-preview');v.srcObject=captureStream;await v.play();if(audioCtx)await audioCtx.close();audioCtx=new AudioContext();analyser=audioCtx.createAnalyser();analyser.fftSize=512;analyser.smoothingTimeConstant=.55;audioData=new Uint8Array(analyser.fftSize);audioCtx.createMediaStreamSource(captureStream).connect(analyser);$('#capture-state').textContent=captureStream.getAudioTracks().length?'LIVE · VIDEO + SYSTEM AUDIO':'LIVE · NO SYSTEM AUDIO'}catch(e){captureStream=null;analyser=null;$('#capture-state').textContent='CAPTURE FAILED';toast('Capture failed: '+e.message)}}
function musicColor(){const calm=sampleScreen();if(!analyser)return calm;analyser.getByteTimeDomainData(audioData);let sum=0;for(const x of audioData){const n=(x-128)/128;sum+=n*n}const rms=Math.sqrt(sum/audioData.length);peak=Math.max(rms,peak*.82);const level=Math.min(1,rms*7),hit=Math.min(1,Math.max(0,(level-.42)/.58)),hot=[255,8,18];const c=calm.map((x,i)=>Math.round(x+(hot[i]-x)*hit));$('#capture-state').textContent=`SCREEN + MUSIC · ${Math.round(level*100)}%${hit>.7?' · RED HIT':''}`;return c}
function sampleScreen(){const v=$('#capture-preview'),cv=$('#capture-canvas');if(!captureStream||v.readyState<2)return lastColor;const ctx=cv.getContext('2d',{willReadFrequently:true});ctx.drawImage(v,0,0,cv.width,cv.height);const d=ctx.getImageData(0,0,cv.width,cv.height).data,bins=Array.from({length:12},()=>({w:0,r:0,g:0,b:0,n:0}));for(let i=0;i<d.length;i+=16){const R=d[i],G=d[i+1],B=d[i+2],mx=Math.max(R,G,B),mn=Math.min(R,G,B),delta=mx-mn;if(mx<22||delta<10)continue;let h;if(mx===R)h=((G-B)/delta+6)%6;else if(mx===G)h=(B-R)/delta+2;else h=(R-G)/delta+4;h*=60;const sat=delta/mx,val=mx/255,q=Math.sqrt(sat)*(.35+.65*val);const bin=bins[Math.floor(h/30)%12];bin.w+=q;bin.r+=R*q;bin.g+=G*q;bin.b+=B*q;bin.n++}const best=bins.reduce((a,b)=>(b.w*(1+Math.log1p(b.n)*.12))>(a.w*(1+Math.log1p(a.n)*.12))?b:a);if(best.w>.1){const raw=[best.r/best.w,best.g/best.w,best.b/best.w];lastColor=raw.map((x,i)=>Math.round(lastColor[i]*.18+x*.82))}const hex='#'+lastColor.map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase();$('#screen-hex').textContent=hex;$('#screen-swatch').style.background=hex;return lastColor}
async function frame(){if(!running||busy)return;busy=true;try{const speed=+$('#speed').value/100,bright=+$('#brightness').value/100;base=hexrgb($('#color').value);let c=base;if(effect==='spectrum')c=hsv((t*90*speed)%360,.82,bright);if(effect==='breathing'){const k=(.2+.8*(Math.sin(t*3*speed)+1)/2)*bright;c=base.map(x=>Math.round(x*k))}if(effect==='wave')c=hsv((t*130*speed)%360,.65,bright);if(effect==='static')c=base.map(x=>Math.round(x*bright));if(effect==='screen')c=sampleScreen().map(x=>Math.round(x*bright));if(effect==='music')c=musicColor().map(x=>Math.round(x*bright));const root=document.documentElement;root.style.setProperty('--accent',`rgb(${c})`);root.style.setProperty('--live',`${c[0]},${c[1]},${c[2]}`);await window.rgb.setFrame({red:c[0],green:c[1],blue:c[2],brightness:Math.round(bright*255),useRazer:$('#use-razer').checked,useSoyo:$('#use-soyo').checked,useAres:$('#use-ares').checked})}catch(e){toast(String(e).slice(0,120))}finally{busy=false;t+=.033}}
async function loadSources(){const list=await window.rgb.screenSources(),sel=$('#capture-source');sel.innerHTML='';list.forEach(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=s.name;o.selected=s.selected;sel.append(o)});$('#capture-state').textContent=list.length?'READY':'NO SOURCES'}
setInterval(frame,33);document.querySelectorAll('[data-effect]').forEach(b=>b.onclick=async()=>{document.querySelectorAll('[data-effect]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');effect=b.dataset.effect;const isScreen=effect==='screen',isMusic=effect==='music',isCapture=isScreen||isMusic;$('#effect-title').textContent=b.textContent.trim();$('#capture').classList.toggle('visible',isCapture);$('#speed-control').hidden=isCapture;$('#base-color').hidden=isCapture;$('#screen-color').hidden=!isScreen;$('#capture-source').hidden=isMusic;if(isCapture){await loadSources();await startCapture()}});$('#capture-source').onchange=async e=>{await window.rgb.selectScreenSource(e.target.value);await startCapture();toast('Capture source selected')};
$('#speed').oninput=e=>$('#speed-out').textContent=e.target.value+'%';$('#brightness').oninput=e=>$('#bright-out').textContent=e.target.value+'%';$('#color').oninput=e=>$('#hex').textContent=e.target.value.toUpperCase();$('#master').onclick=e=>{running=!running;e.currentTarget.classList.toggle('on',running);e.currentTarget.innerHTML=running?'<span>●</span> SYNC ACTIVE':'<span>●</span> SYNC PAUSED'};
async function refresh(){try{const s=await window.rgb.status();for(const k of ['soyo','razer','ares']){$(`[data-device="${k}"]`).classList.toggle('connected',s[k]);$(`[data-device="${k}"]`).classList.toggle('offline',!s[k])}toast('Devices refreshed')}catch(e){toast(e)}}$('#refresh').onclick=refresh;refresh();loadSources().then(startCapture);
